### ISSUE TITLE
Perhaps extend to `Object` by default?

### ISSUE THREAD

**Issue by jimmynguyc** [edisonywh/behaves#8]
I ended up adding this as an initializer
```ruby
Object.send :extend, Behaves
``` 
to avoid typing `extend Behave` all the time.

**Comment by edisonywh** [comment]
👋thanks for the issue Jimmy!

Great point! I had thought about this, but I'm not fond of the idea of forcing `Behaves` on the users. But perhaps we can add a section on the README that shows how to do it, just like what you did here.

**Comment by PikachuEXE** [comment]
I prefer opt-in over opt-out (not to say you can't opt-out once extended)

**Comment by jimmynguyc** [comment]
👍 on the README addition
